[tools]
elixir = "1.19.5"

[env]
_.file = '.env'
MIX_DEPS_PATH = "deps"

[tasks.update-zeabur-template]
description = "Update Zeabur template"
run = [
  "echo 'Updating Zeabur template...'",
  "npx zeabur template update -c FTAONK -f others/zeabur/template.yaml",
  "echo '✅ https://zeabur.com/templates/FTAONK'",
]

[tasks.up]
description = "Up containers"
run = [
    "docker compose up -d"
]

[tasks.dev]
description = "Run dev"
run = [
    "mix ts.migrate",
    "iex -S mix run --no-halt"
]

[tasks.start]
description = "Run start"
run = [
    "docker compose --profile prod up -d"
]

[tasks.stop]
description = "Stop start"
run = [
    "docker compose --profile prod down"
]

[tasks.build]
description = "Build the acceptance testing image locally"
run = [
  "docker build -t save_it:e2e .",
]
