# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: SaveIt
spec:
  description: SaveIt is a telegram bot that helps you save photos.
  icon: https://raw.githubusercontent.com/ThaddeusJiang/save_it/refs/heads/main/docs/assets/savt_it_bot_logo.jpg
  tags:
    - Bot
    - Telegram
    - Photos Storage
    - Search Engine
  coverImage: https://raw.githubusercontent.com/ThaddeusJiang/save_it/refs/heads/main/docs/assets/savt_it_demo.gif

  readme: |-
    # SaveIt
    A telegram bot can Save photos and Search photos

    ##  Features
    - Save photos via a link
    - Search photos using semantic search
    - Find similar photos by photo

    [more](https://github.com/ThaddeusJiang/save_it)

  services:
    - name: save_it
      icon: https://raw.githubusercontent.com/ThaddeusJiang/save_it/refs/heads/main/docs/assets/savt_it_bot_logo.jpg
      template: GIT
      spec:
        source:
          source: GITHUB
          repo: 831394769
          branch: main
          rootDirectory: /
        env:
          TELEGRAM_BOT_TOKEN:
            default: ""
            expose: false
          COBALT_API_URL:
            default: http://cobalt-api.zeabur.internal:9000
            expose: false
          TYPESENSE_URL:
            default: http://typesense.zeabur.internal:8108
            expose: false
          TYPESENSE_API_KEY:
            default: ${TYPESENSE_API_KEY}
            expose: false
          GOOGLE_OAUTH_CLIENT_ID:
            default: ""
            expose: false
          GOOGLE_OAUTH_CLIENT_SECRET:
            default: ""
            expose: false
        configs: []
    - name: typesense
      icon: https://typesense.org/docs/images/typesense_logo.svg
      template: PREBUILT_V2
      spec:
        source:
          image: typesense/typesense:27.1
        ports:
          - id: web
            port: 8108
            type: HTTP
        volumes:
          - id: data
            dir: /data
        instructions:
          - type: PASSWORD
            title: Typesense API Key
            content: ${TYPESENSE_API_KEY}
            category: Credentials
        env:
          TYPESENSE_API_KEY:
            default: ${PASSWORD}
            expose: true
          TYPESENSE_DATA_DIR:
            default: /data
            expose: false

        configs: []
    - name: cobalt-api
      icon: https://github.com/imputnet/cobalt/raw/main/web/static/favicon.png
      template: PREBUILT_V2
      spec:
        source:
          image: ghcr.io/imputnet/cobalt:10
        ports:
          - id: api
            port: 9000
            type: TCP
        env:
          API_URL:
            default: undefined
            expose: false

        configs: []
